site_name: doris-analysis
site_description: Documentation for the master's thesis project MasterThesis-DorisAnalysis
site_url: https://kovarmi9.github.io/MasterThesis-DorisAnalysis/

theme:
  name: material

plugins:
  - search
  - include-markdown

docs_dir: docs_src

nav:
  - Home: index.md
  - Repository structure: structure.md
  - Installation: installation.md
  - Input data: input.md
  - Station analysis: stations.md
  - Orbit comparison: orbits.md
  - Outputs: output.md
  - Repository: https://github.com/kovarmi9/MasterThesis-DorisAnalysis
